import React from 'react'
import Footer from '../components_main/Footer'
import style  from '@/styles/Layout_main/Layout.module.css';
import NavBar from '../components_main/NavBar';
import Header from '../components_main/Header';
import Head from 'next/head';
import Link from 'next/link'
function Layout({children}) {
  return (
    <div className={style.container}>
       <Head>
        <title>BookingApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/booking-icon-png-10.ico" type="image/x-icon" />
        <meta name="description" content="Booking app" />
      </Head>
         <NavBar />
         <Header list = {true} />
         {children}
         <Footer/>
    </div>
  )
}

export default Layout